export const ASSET_TYPE_COIN = 'COIN';
export const ASSET_TYPE_TOKEN = 'TOKEN';

export const CHAIN_LIST_MAP = {
    ALL: ['eth', 'bsc', 'polygon'],
    BSC: ['bsc'],
    ETH: ['eth'],
    POLYGON: ['polygon'],
};
export const CHAIN_ID_MAP = {
    ETH: 1,
    BSC: 56,
    POLYGON: 137,
    TRON: 999,
    ARB: 42161,
    BTTC: 199,
};
export const CHAIN_ID_TYPE_MAP = {
    1: 'ETH',
    56: 'BSC',
    137: 'POLYGON',
    999: 'TRON',
    199: 'BTTC',
    42161: 'ARB',
};
export const CHAIN_TO_SYMBOL_MAP = {
    ETH: 'ETH',
    BSC: 'BNB',
    POLYGON: 'MATIC',
    TRON: 'TRX',
    ARB: 'ETH',
    BTTC: 'BTTC',
};
export const btc = {
    order: 0,
    symbol: 'BTC',
    name: 'Bitcoin',
    id: 'bitcoin',
    chain: 'BTC',
    type: ASSET_TYPE_COIN,
    decimals: 8,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://assets.coingecko.com/coins/images/1/large/bitcoin.png',
};
export const eth = {
    order: 2,
    symbol: 'ETH',
    name: 'Ethereum',
    id: 'ethereum',
    chain: 'ETH',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://assets.coingecko.com/coins/images/279/large/ethereum.png',
};
export const bsc = {
    order: 3,
    symbol: 'BNB',
    name: 'Binance Coin',
    id: 'binancecoin',
    chain: 'BSC',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://assets.coingecko.com/coins/images/825/large/binance-coin-logo.png',
};
export const polygon = {
    order: 4,
    symbol: 'MATIC',
    name: 'Matic',
    id: 'matic-network',
    chain: 'POLYGON',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://assets.coingecko.com/coins/images/4713/large/matic-token-icon.png',
};
export const tron = {
    order: 5,
    symbol: 'TRX',
    name: 'Tron',
    id: 'tron',
    chain: 'TRON',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1958.png',
};

export const dai_eth = {
    symbol: 'DAI',
    name: 'Dai',
    id: 'dai',
    chain: 'ETH',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x6B175474E89094C44Da98b954EedeAC495271d0F',
    privKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://assets.coingecko.com/coins/images/9956/large/4943.png',
};
export const link_eth = {
    symbol: 'LINK',
    name: 'Chainlink',
    id: 'chainlink',
    chain: 'ETH',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x514910771AF9Ca656af840dff83E8264EcF986CA',
    privKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://assets.coingecko.com/coins/images/877/large/chainlink-new-logo.png',
};
export const mana_eth = {
    symbol: 'MANA',
    name: 'Decentraland',
    id: 'decentraland',
    chain: 'ETH',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x0F5D2fB29fb7d3CFeE444a200298f468908cC942',
    privKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://assets.coingecko.com/coins/images/878/large/decentraland-mana.png',
};
export const uni_eth = {
    symbol: 'UNI',
    name: 'Uniswap',
    id: 'uniswap',
    chain: 'ETH',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984',
    privKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://assets.coingecko.com/coins/images/12504/large/uniswap-uni.png',
};
export const arb = {
    order: 7,
    symbol: 'ARB',
    name: 'Arbitrum',
    id: 'arbitrum',
    chain: 'ARB',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x912CE59144191C1204E64559FE8253a0e49E6548',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://s2.coinmarketcap.com/static/img/coins/64x64/11841.png',
};
export const bttc = {
    symbol: 'BTT',
    name: 'BitTorrent',
    id: 'bittorrent',
    chain: 'BTTC',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://s2.coinmarketcap.com/static/img/coins/64x64/16086.png',
};

export const pcb = {
    order: 2,
    symbol: 'PCB',
    name: 'PentaCoin',
    id: 'pentacoin',
    chain: 'ARB',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x02caEFC9083AFCD630beFdB2e67EC73FC3b2B42B',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://pentawallet.herokuapp.com/content/pentacoin.png',
};
